//! Ticket summaries: a short English summary and purpose for every available
//! ticket, generated by the chat model.
//!
//! [`ticket_prompt`] builds the prompt for one ticket (key, type, parent,
//! title and a capped description); the model answers with a
//! [`TicketSummary`], which [`validate_summary`] checks for blank and overlong
//! fields. The summaries stage in [`crate::indexer`] runs it for every
//! available ticket and stores the result in the index `tickets` table. Later
//! prompts (method and type what/why) take these summaries as their "why"
//! context, so they are short and say why the change was needed.
//!
//! [`Summarizer`] is the LLM client plus the stage's mode: `cache_only` uses
//! summaries already in the LLM cache and never calls the model (`--no-llm`).

use anyhow::Result;
use schemars::JsonSchema;
use serde::Deserialize;

use crate::config::OllamaConfig;
use crate::jira::Ticket;
use crate::llm::LlmClient;
use crate::store::Store;

/// Longest description, in characters, that goes into a prompt; a longer one
/// is cut and marked as truncated.
pub const MAX_DESCRIPTION_CHARS: usize = 4000;

/// Longest accepted `summary`, in characters (the prompt asks for 300).
pub const MAX_SUMMARY_CHARS: usize = 400;

/// Longest accepted `purpose`, in characters (the prompt asks for 200).
pub const MAX_PURPOSE_CHARS: usize = 300;

/// What the chat model returns for one ticket.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct TicketSummary {
    /// One or two sentences in English: what the ticket asks for or changes.
    pub summary: String,
    /// One sentence in English: why it was needed.
    pub purpose: String,
}

/// The prompt for `ticket`. `parent_title` is the parent's title when the
/// parent is a known ticket too.
pub fn ticket_prompt(ticket: &Ticket, parent_title: Option<&str>) -> String {
    let mut prompt = format!(
        "\
You summarise one Jira ticket for developers who read code that was changed for it. \
Your answer is shown next to that code to explain why the code exists.

The ticket may be written in German or English. Always answer in English. \
Use only what the ticket says and do not invent details. \
Keep product names, technical identifiers and ticket keys exactly as written.

Answer with two fields:
- summary: one or two sentences, at most 300 characters, saying what the ticket asks for or changes.
- purpose: one sentence, at most 200 characters, saying why it was needed: the problem, goal or user need behind it. \
If the ticket does not state a reason, give the most likely one its content supports.

Ticket: {}
Type: {}
",
        ticket.key, ticket.issue_type
    );
    if let Some(parent) = &ticket.parent_key {
        match parent_title {
            Some(title) => prompt.push_str(&format!("Parent: {parent} ({title})\n")),
            None => prompt.push_str(&format!("Parent: {parent}\n")),
        }
    }
    prompt.push_str(&format!("Title: {}\n", ticket.summary));
    match ticket
        .description
        .as_deref()
        .map(str::trim)
        .filter(|description| !description.is_empty())
    {
        Some(description) => {
            prompt.push_str("Description:\n");
            prompt.push_str(&capped(description, MAX_DESCRIPTION_CHARS));
            prompt.push('\n');
        }
        None => prompt.push_str("Description: (none)\n"),
    }
    prompt
}

/// `text` cut to `max` characters, with a marker when it was cut.
fn capped(text: &str, max: usize) -> String {
    match text.char_indices().nth(max) {
        Some((end, _)) => format!("{}\n[description truncated]", text[..end].trim_end()),
        None => text.to_string(),
    }
}

/// Reject a blank or overlong field; the message goes back to the model.
pub fn validate_summary(summary: &TicketSummary) -> Result<(), String> {
    check_field("summary", &summary.summary, MAX_SUMMARY_CHARS)?;
    check_field("purpose", &summary.purpose, MAX_PURPOSE_CHARS)
}

fn check_field(name: &str, value: &str, max: usize) -> Result<(), String> {
    if value.trim().is_empty() {
        return Err(format!("`{name}` is blank"));
    }
    let chars = value.chars().count();
    if chars > max {
        return Err(format!(
            "`{name}` has {chars} characters; keep it under {max}"
        ));
    }
    Ok(())
}

/// The LLM client the summaries stage calls, and whether it may call the
/// model at all.
pub struct Summarizer {
    pub(crate) client: LlmClient,
    /// Use cached summaries only; never call the chat model.
    pub(crate) cache_only: bool,
}

impl Summarizer {
    pub fn new(client: LlmClient, cache_only: bool) -> Self {
        Self { client, cache_only }
    }

    /// The client, e.g. for its [`crate::llm::LlmStats`].
    pub fn client(&self) -> &LlmClient {
        &self.client
    }

    /// The summarizer for an `index` run, or `None` without an `[ollama]`
    /// section (one warning; tickets get no summary). `no_llm` keeps the
    /// cached summaries but makes no chat call. The client gets its own
    /// `cache.db` connection.
    pub fn from_config(
        ollama: Option<&OllamaConfig>,
        no_llm: bool,
        store: &Store,
    ) -> Result<Option<Self>> {
        let Some(ollama) = ollama else {
            tracing::warn!("no [ollama] section in the config; tickets get no summaries");
            return Ok(None);
        };
        if no_llm {
            tracing::info!("--no-llm: no chat calls; using cached summaries only");
        }
        let client = LlmClient::from_config(ollama, store.connect_cache()?)?;
        Ok(Some(Self::new(client, no_llm)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ticket() -> Ticket {
        Ticket {
            key: "GRLD-7".to_string(),
            issue_type: "Verbesserung".to_string(),
            summary: "Export Validierung verbessern".to_string(),
            description: Some("Ungültige Datensätze früh erkennen.".to_string()),
            parent_key: Some("GRLD-1".to_string()),
        }
    }

    fn summary(summary: &str, purpose: &str) -> TicketSummary {
        TicketSummary {
            summary: summary.to_string(),
            purpose: purpose.to_string(),
        }
    }

    #[test]
    fn prompt_carries_every_ticket_field() {
        let prompt = ticket_prompt(&ticket(), Some("Export rework"));

        assert!(prompt.contains("Always answer in English."), "{prompt}");
        assert!(
            prompt.ends_with(
                "\
Ticket: GRLD-7
Type: Verbesserung
Parent: GRLD-1 (Export rework)
Title: Export Validierung verbessern
Description:
Ungültige Datensätze früh erkennen.
"
            ),
            "{prompt}"
        );
    }

    #[test]
    fn prompt_without_parent_title_parent_or_description() {
        let prompt = ticket_prompt(&ticket(), None);
        assert!(prompt.contains("\nParent: GRLD-1\n"), "{prompt}");

        let bare = Ticket {
            parent_key: None,
            description: Some("  \n".to_string()),
            ..ticket()
        };
        let prompt = ticket_prompt(&bare, Some("ignored"));
        assert!(!prompt.contains("Parent:"), "{prompt}");
        assert!(
            prompt.ends_with("Title: Export Validierung verbessern\nDescription: (none)\n"),
            "{prompt}"
        );
        let none = Ticket {
            description: None,
            ..bare
        };
        assert_eq!(ticket_prompt(&none, None), prompt);
    }

    #[test]
    fn long_description_is_capped_on_a_char_boundary() {
        let long = Ticket {
            description: Some("ä".repeat(MAX_DESCRIPTION_CHARS + 10)),
            ..ticket()
        };
        let prompt = ticket_prompt(&long, None);
        let description = prompt.split("Description:\n").nth(1).unwrap();

        assert_eq!(
            description,
            format!(
                "{}\n[description truncated]\n",
                "ä".repeat(MAX_DESCRIPTION_CHARS)
            )
        );
        let exact = Ticket {
            description: Some("ä".repeat(MAX_DESCRIPTION_CHARS)),
            ..ticket()
        };
        assert!(!ticket_prompt(&exact, None).contains("truncated"));
    }

    #[test]
    fn prompt_is_stable() {
        assert_eq!(
            ticket_prompt(&ticket(), Some("Export rework")),
            ticket_prompt(&ticket(), Some("Export rework")),
            "the prompt is the cache key; it must not vary between runs"
        );
    }

    #[test]
    fn validation_rejects_blank_and_overlong_fields() {
        assert_eq!(
            validate_summary(&summary("Adds X.", "Users need X.")),
            Ok(())
        );
        assert_eq!(
            validate_summary(&summary(" ", "Users need X.")),
            Err("`summary` is blank".to_string())
        );
        assert_eq!(
            validate_summary(&summary("Adds X.", "")),
            Err("`purpose` is blank".to_string())
        );
        let err = validate_summary(&summary(&"x".repeat(MAX_SUMMARY_CHARS + 1), "Why."))
            .expect_err("overlong summary");
        assert!(err.contains("`summary` has 401 characters"), "{err}");
        assert!(validate_summary(&summary(&"x".repeat(MAX_SUMMARY_CHARS), "Why.")).is_ok());
        let err = validate_summary(&summary("Adds X.", &"y".repeat(MAX_PURPOSE_CHARS + 1)))
            .expect_err("overlong purpose");
        assert!(err.contains("`purpose`"), "{err}");
    }

    #[test]
    fn schema_rejects_unknown_fields() {
        let schema = serde_json::to_value(schemars::schema_for!(TicketSummary)).unwrap();
        assert_eq!(
            schema["required"],
            serde_json::json!(["summary", "purpose"])
        );
        assert_eq!(schema["additionalProperties"], serde_json::json!(false));
        assert!(
            serde_json::from_str::<TicketSummary>(
                r#"{"summary": "a", "purpose": "b", "extra": 1}"#
            )
            .is_err()
        );
    }

    #[tokio::test]
    async fn no_ollama_section_means_no_summarizer() {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path()).await.unwrap();
        assert!(
            Summarizer::from_config(None, false, &store)
                .unwrap()
                .is_none()
        );
        let ollama = OllamaConfig {
            url: "http://localhost:11434".to_string(),
            chat_model: "chat".to_string(),
            embedding_model: "embed".to_string(),
            reasoning_effort: "none".to_string(),
            temperature: 0.0,
        };
        let summarizer = Summarizer::from_config(Some(&ollama), true, &store)
            .unwrap()
            .expect("configured");
        assert!(summarizer.cache_only);
    }
}
